### PR TITLE
Added Responsive styles to home page 

### PR DESCRIPTION
**Pull request by akshpnwr**

### CODE REVIEW

**Review by karmveerranawat — CHANGES_REQUESTED** [review]
1st make pr on testing branch.
2nd follow readme.md architecture naming.

**Comment by karmveerranawat** [comment]
Dev branch is being deleted , sorry for inconvinience

**Comment by akshpnwr** [comment]
Do you want the landing page's CSS and JS files inside their respective pages directory?

- like this 

image

**Comment by karmveerranawat** [comment]
kind of like this and sorry for enforcing this so badly , only doing this so that everything stays isolated and easy to modify..
the pages folder can further have folder based on pages name. something like if there is page page1.html which uses page1.css and page1.js
then page1.css could be found in /assets/styles/pages/page1/page1.css
similarly page1.js could be found in /assets/scripts/pages/page1/page1.js

it seems tedious as of now and doesn't make sense , but it will be helpful when site features increase and there are multiple contributors

*the index.html has to be placed in root folder where there is assets folder and pages folder...
other pages then can go under /pages

**Comment by akshpnwr** [comment]
Totally understandable. index is already in the root folder
- scripts/pages/landing/landing.js
- styles/pages/landing/landing.css
is this ok?

**Comment by karmveerranawat** [comment]
1. ok if its outside in root then great it just seemed like its inside pages
2. yes perfect

**Comment by akshpnwr** [comment]
It's because the pages folder is empty.
Great!. I'll change it and raise a PR.

**Comment by karmveerranawat** [comment]
gotcha! 
cool
once your pr is closed on testing branch , it will auto deployed and you can see the site at testing.dehashed.in

**Pull request closed without merging**
